import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

export async function getStaticProps() {
  console.log("Getting Static Props ");
  let headers = {};

  headers["Content-Type"] = "application/json";

  var graphql = JSON.stringify({
    query: `query moralisQuery {
    moralisQuery(chain: "eth", x_api_key: "dDxWDZNNCNTu5DAkZaRj8DIIWBeb02jGI4f1gUW2tkIANXcEUnGlkOB7XZCiQuyy"){
        cursor
        page
        page_size
        result{
            address
            block_hash
            block_number
            block_timestamp
            data
            topic0
            topic1
            topic2
            topic3
            transaction_hash
        }
        total
    }
}`,
  });

  var requestOptions = {
    method: "POST",
    headers: headers,
    body: graphql,
  };

  console.log("before fetch");
  fetch(
    "https://publicbaf08be93829ae40.stepzen.net/api/moralis/__graphql",
    requestOptions
  )
    .then((response) => console.log(response.text()))
    .then((result) => console.log(result))
    .catch((error) => console.log("error", error));

  return {
    props: {
      //posts,
    },
    // Next.js will attempt to re-generate the page:
    // - When a request comes in
    // - At most once every 10 seconds
    revalidate: 1, // In seconds
  };
}

export default Home;
